### ISSUE TITLE
:sparkles: Upload 21cmdata to repository :sparkles:

### ISSUE THREAD

**Issue by paulomontero** [CosmoSheep/reion_ns#1]
Required data is crosspower spectrum of matter and neutral hydrogen fraction and the neutral hydrogen history.
- [x] Upload the 4 realizations of Early model
- [x] Upload the 4 realizations of Late model
- [x] Upload the 4 realizations of Planck model
- [x] Compute the average for all models
- [x] Upload the reionization histories

**Comment by catamorales** [comment]
For the Planck model, there are 3 realizations. There is one left to do
